namespace Last_Rich_Presence
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        void InitWindow();
        void OnEnableToggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void OnNavSelectionChanged(Microsoft.UI.Xaml.Controls.NavigationView sender, Microsoft.UI.Xaml.Controls.NavigationViewSelectionChangedEventArgs args);
        void OnTimestampToggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void OnSourceToggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void OnPausedToggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void OnAlbumArtToggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
    }
}
